name:           Unbridled Cynicism
description:    less bullshit, more often?
url:            http://j.furinkan.meidokon.net
destination:    /home/furinkan/public_html/j.furinkan.meidokon.net
atom_path:      /feeds/atom.xml
rss_path:       /feeds/rss.xml
pygments:       true
# MaRuKu can't do nested lists properly - https://github.com/mojombo/jekyll/issues/190
markdown:       rdiscount
img_full_path:  /img/full
img_thumb_path: /img/thumb
comrades:
- ["AstCd2 @ Mikanya", "http://mikanya.meidokon.net/"]
- ["Akira @ Moe Fundamentalism", "http://akirascuro.wordpress.com/"]
